name: CI

on:
  push:
    branches: [ main, hshim023/Rectangle ]
  pull_request:
    branches: [ main ]
   

# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Rectangle tests
      run: |
       cmake .
       make
       ./bin/runAllTests
